[Rainmeter]
Update=1000
BackgroundMode=2
SolidColor=15,15,15,200

[Metadata]
Name=System Monito
Author=Leaandroo
Description=Monitor de CPU, GPU, RAM y Red.

[MeasureCPU]
Measure=CPU

[MeasureGPU]
Measure=Plugin
Plugin=UsageMonitor
Alias=GPU
Index=0

[MeasureRAM]
Measure=PhysicalMemory

[MeasureRedIn]
Measure=NetIn

[MeasureRedOut]
Measure=NetOut

[StyleText]
FontColor=255,255,255,255
FontFace=Consolas
FontSize=11
AntiAlias=1
X=10
Y=5R

; ========================================
; METERS - Muestran los datos
; ========================================

[MeterTitulo]
Meter=String
MeterStyle=StyleText
Y=10
X=40
FontWeight=700
Text=RENDIMIENTO

[MeterLinea]
Meter=Image
SolidColor=255,255,255,50
X=10
Y=5R
W=150
H=1

[MeterCPU]
Meter=String
MeterStyle=StyleText
MeasureName=MeasureCPU
Text=CPU: %1%

[MeterGPU]
Meter=String
MeterStyle=StyleText
Text=GPU: [MeasureGPU:0]%
DynamicVariables=1

[MeterRAM]
Meter=String
MeterStyle=StyleText
MeasureName=MeasureRAM
Text=RAM: %1B ([MeasureRAM:%,0]%)
AutoScale=1
NumOfDecimals=1
DynamicVariables=1


[MeterRedIn]
Meter=String
MeterStyle=StyleText
MeasureName=MeasureRedIn
Text=DL: %1b/s
AutoScale=1

[MeterRedOut]
Meter=String
MeterStyle=StyleText
MeasureName=MeasureRedOut
Text=UP: %1b/s
AutoScale=1

[MeterMargenInferior]
Meter=Image
X=0
Y=0R
W=170
H=10
SolidColor=0,0,0,0