[Rainmeter]
Update=1000
BackgroundMode=2
SolidColor=0,0,0,1

[Metadata]
Name=System Monitor
Author=Leaandroo
Description=Monitor de uso de CPU, GPU, RAM y Red.

[MeasureCPU]
Measure=CPU

[MeasureGPU]
Measure=Plugin
Plugin=UsageMonitor
Alias=GPU
Index=0

[MeasureRAM]
Measure=PhysicalMemory

;Medida de red bajada
[MeasureRedDown]
Measure=NetIn

;Lo convertimos a bits
[MeasureRedDownBits]
Measure=Calc
Formula=MeasureRedDown * 8

;Medida de Red Subida
[MeasureRedUp]
Measure=NetOut
;Lo convertimos a bits
[MeasureRedUpBits]
Measure=Calc
Formula=MeasureRedUp * 8

[StyleText]
FontColor=255,255,255,255
FontStyle=Bold
FontFace=Consolas
FontSize=12
AntiAlias=1
X=10
Y=5R
InlineSetting=Shadow | 0 | 0 | 5 | 0,0,0,255

; ========================================
; METERS - Muestran los datos
; ========================================

[MeterCPU]
Meter=String
MeterStyle=StyleText
MeasureName=MeasureCPU
Text=CPU: %1%

[MeterGPU]
Meter=String
MeterStyle=StyleText
Text=GPU: [MeasureGPU:0]%
DynamicVariables=1

[MeterRAM]
Meter=String
MeterStyle=StyleText
MeasureName=MeasureRAM
Text=RAM: %1B ([MeasureRAM:%,0]%)
AutoScale=1
NumOfDecimals=1
DynamicVariables=1


[MeterRedDown]
Meter=String
MeterStyle=StyleText
MeasureName=MeasureRedDownBits
Text=Down: %1b/s
AutoScale=1

[MeterRedOut]
Meter=String
MeterStyle=StyleText
MeasureName=MeasureRedUpBits
Text=Up: %1b/s
AutoScale=1

[MeterMargenInferior]
Meter=Image
X=0
Y=0R
W=180
H=10
SolidColor=0,0,0,0